export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const BASKET_ROUTE = '/baskets'
export const PRODUCTS_ROUTE = '/products'
export const ABOUT_ROUTE='/about'
