export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const BASKET_ROUTE = '/baskets'
export const PRODUCTS_ROUTE = '/products'
export const ABOUT_ROUTE = '/about'
export const AUTH_ROUTE = '/auth'
export const BASE_URL = 'https://asoldatov-online-store-back.herokuapp.com'
